name: Publish package
run-name: Publish package triggered by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release Type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Create a release workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.1

      - name: Install dependencies
        run: pnpm install

      - name: Bump version and create trigger commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config advice.ignoredHook false
          npm version --no-git-tag-version ${{ github.event.inputs.releaseType }}
          RELEASE_TYPE=$(echo "${{ github.event.inputs.releaseType }}" | tr '[:lower:]' '[:upper:]')
          RELEASE_VERSION=$(node -p "require('./package.json').version")
          git add package.json
          git commit -m "RELEASE_$RELEASE_TYPE: publish version $RELEASE_VERSION"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create sync pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base dev --head main --title "[Release Sync]: main to dev" --body "This PR syncs changes from the `main` branch to the `dev` branch."

      - name: Build library
        run: |
          git checkout main
          pnpm build

      - name: Semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
